language: node_js
os:
  - "linux"
dist:
  - "dist/crm/"
node_js:
  - "13.7.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
  - npm install
  - npm run build
after_script:
  - firebase deploy --only hosting --token $FIREBASE_TOKEN