on:
  push:
    branches:
      - master
jobs:
  build_app:
    name: build app
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: '13.7.0'
          
      - name: install and build
        run: |
          npm install
          npm run build --if-present
