on:
  push:
    branches:
      - master
jobs:
  build_app:
    name: build app
    runs-on: ubuntu-latest
    steps:
      - name: Setup node version
        uses: actions/setup-node@v1
        with:
          node-version: '13.7.0'
          
      - name: install
        run: npm install
      
      - name: build
        run: npm run build
